apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitlab
spec:
  replicas: 1
  minReadySeconds: 30
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      name: gitlab
  template:
    metadata:
      labels:
        name: gitlab
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:12.7.5-ce.0
        volumeMounts:
          - name: config
            mountPath: /etc/gitlab
          - name: data
            mountPath: /var/opt/gitlab
          - name: log
            mountPath: /var/log/gitlab
        volumes:
        - name: config
          nfs:
            path: /srv/gitlab/config
            server: 192.168.100.200
        - name: data
          nfs:
            path: /srv/gitlab/data
            server: 192.168.100.200
        - name: log
          nfs:
            path: /srv/gitlab/logs
            server: 192.168.100.200
