apiVersion: v1
kind: Service
metadata:
  name: gitlab-80
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 10080
  selector:
    name: gitlab
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-443
spec:
  type: NodePort
  ports:
    - port: 443
      targetPort: 443
      nodePort: 10043
  selector:
    name: gitlab
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-22
spec:
  type: NodePort
  ports:
    - port: 22
      targetPort: 22
      nodePort: 10022
  selector:
    name: gitlab
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-4040
spec:
  type: NodePort
  ports:
    - port: 4040
      targetPort: 4040
      nodePort: 10040
  selector:
    name: gitlab